name: packer-ami-copy
description: build a packer template and copy it to any number of other accounts
author: https://github.com/envato
requirements:
  - aws
  - docker
configuration:
  properties:
    packer_commands:
      type:
        - string
        - array
    packer_template:
      type: string
    chdir:
      type: string
    env_vars:
      type: array
    load_artifacts:
      type: array
    prep_commands:
      type: array
  required:
    - packer_commands
    - packer_template
